### PR TITLE
LAUNCHPAD_<browser> & LAUNCHPAD_BROWSERS env vars

### PR DESCRIPTION
**Pull request by mazswojejzony**
This PR is related to issue #51.

### CODE REVIEW

**Comment by MeTaNoV** [comment]
:+1:

**Comment by daffl** [comment]
Awesome, looks good! It is missing some docs however. If you add those to the readme I can get out a 0.5.0 right away.

**Comment by mazswojejzony** [comment]
Yeah, I was going to update the readme but somehow I didn't. :-)

**Comment by mazswojejzony** [comment]
I've added an ability to define more than one default location. Existing tests cover the changes. This is also kind of internal behavior hence no docs update.

**Comment by daffl** [comment]
Awesome, thank you! I just published version 0.5.0. If you have another minute, an update in the changelog would also be great but the release is good to go.

**Comment by mazswojejzony** [comment]
I've just raised another PR with changelog update: #54. Not sure if I did it correctly git-wise though.

**Comment by daffl** [comment]
Yep that's great. Thank you again!

**Pull request merged**
